name: Sonar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarScanner for .NET 7 with pull request decoration support
        uses: highbyte/sonarscan-dotnet@v2.2.1
        with:
          # The key of the SonarQube project
          sonarProjectKey: your_projectkey
          # The name of the SonarQube project
          sonarProjectName:  your_projectname
          # The SonarQube server URL. For SonarCloud, skip this setting.
          sonarHostname:  ${{ secrets.SONAR_HOST_URL }}
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
